services:

  AssesmentApiInstance:
    image: redis:latest
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  EvaluationApiInstance:
    image: redis:latest
    ports:
      - 6380:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data2:/data
  
  redis:
    image: redis:latest
    ports:
      - 6381:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data3:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:AssesmentApiInstance:6379,local:EvaluationApiInstance:6379,local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=secret
    ports:
      - 8081:8081
    depends_on:
      - redis
    
volumes:
  redis-data:
  redis-data2:
  redis-data3: