apiVersion: v1
kind: Service
metadata:
  name: authservice-srv
spec:
  type: LoadBalancer
  selector:
    app: authapi
  ports:
    - name: authapi
      protocol: TCP
      port: 80
      targetPort: auth-port